INSERT INTO Pais(nome_pais) VALUES("France"), ("Belgium"), ("Argentina"), ("Poland"), ("Brazil"), ("Croatia"),
("Senegal"), ("England"), ("Netherlands"), ("South Korea"), ("Uruguay"), ("Germany"), ("Portugal"), ("Spain"),
("Canada"), ("Marocco"), ("Serbia"), ("Denmark"), ("Cameroon");

INSERT INTO Figurinha(nome_jogador, id_pais, imagem_jogador)
VALUES("Kylian Mbappe", 1, "/View/Modules/Album/Images/Stickers/Franca/Kylian_Mbappe.jpg"),
("Karim Benzema", 1, "/View/Modules/Album/Images/Stickers/Franca/Karim_Benzema.jpg"),
("Kevin De Bruyne", 2, "/View/Modules/Album/Images/Stickers/Belgica/Kevin_De_Bruyne.jpg"),
("Lionel Messi", 3, "/View/Modules/Album/Images/Stickers/Argentina/Lionel_Messi.jpg"),
("Robert Lewandowski", 4, "/View/Modules/Album/Images/Stickers/Polonia/Robert_Lewandowski.jpg"),
("Neymar", 5, "/View/Modules/Album/Images/Stickers/Brasil/Neymar.jpg"),
("Luka Modric", 6, "/View/Modules/Album/Images/Stickers/Croacia/Luka_Modric.jpg"),
("Vinicius Junior", 5, "/View/Modules/Album/Images/Stickers/Brasil/Vinicius_Junior.jpg"),
("Thibaut Courtois", 2, "/View/Modules/Album/Images/Stickers/Belgica/Thibaut_Courtois.jpg"),
("Sadio Mane", 7, "/View/Modules/Album/Images/Stickers/Senegal/Sadio_Mane.jpg"),
("Harry Kane", 8, "/View/Modules/Album/Images/Stickers/Inglaterra/Harry_Kane.jpg"),
("Virgil van Dijk", 9, "/View/Modules/Album/Images/Stickers/Holanda/Virgil_van_Dijk.jpg"),
("Son Heung-Min", 10, "/View/Modules/Album/Images/Stickers/Coreia_do_Sul/Son_Heung_Min.jpg"),
("Federico Valverde", 11, "/View/Modules/Album/Images/Stickers/Uruguai/Federico_Valverde.jpg"),
("Joshua Kimmich", 12, "/View/Modules/Album/Images/Stickers/Alemanha/Joshua_Kimmich.jpg"),
("Bernardo Silva", 13, "/View/Modules/Album/Images/Stickers/Portugal/Bernardo_Silva.jpg"),
("Joao Cancelo", 13, "/View/Modules/Album/Images/Stickers/Portugal/Joao_Cancelo.jpg"),
("Phil Foden", 8, "/View/Modules/Album/Images/Stickers/Inglaterra/Phil_Foden.jpg"),
("Pedri", 14, "/View/Modules/Album/Images/Stickers/Espanha/Pedri.jpg"),
("Cristiano Ronaldo", 13, "/View/Modules/Album/Images/Stickers/Portugal/Cristiano_Ronaldo.jpg"),
("Alisson", 5, "/View/Modules/Album/Images/Stickers/Brasil/Alisson.jpg"),
("Jude Bellingham", 8, "/View/Modules/Album/Images/Stickers/Inglaterra/Jude_Bellingham.jpg"),
("Ruben Dias", 13, "/View/Modules/Album/Images/Stickers/Portugal/Ruben_Dias.jpg"),
("Manuel Neuer", 12, "/View/Modules/Album/Images/Stickers/Alemanha/Manuel_Neuer.jpg"),
("Casemiro", 5, "/View/Modules/Album/Images/Stickers/Brasil/Casemiro.jpg"),
("Alphonso Davies", 15, "/View/Modules/Album/Images/Stickers/Canada/Alphonso_Davies.jpg"),
("Bruno Fernandes", 13, "/View/Modules/Album/Images/Stickers/Portugal/Bruno_Fernandes.jpg"),
("Rafael Leao", 13, "/View/Modules/Album/Images/Stickers/Portugal/Rafael_Leao.jpg"),
("Marquinhos", 5, "/View/Modules/Album/Images/Stickers/Brasil/Marquinhos.jpg"),
("Antonio Rudiger", 12, "/View/Modules/Album/Images/Stickers/Alemanha/Antonio_Rudiger.jpg"),
("Thomas Muller", 12, "/View/Modules/Album/Images/Stickers/Alemanha/Thomas_Muller.jpg"),
("Frenkie de Jong", 9, "/View/Modules/Album/Images/Stickers/Holanda/Frenkie_de_Jong.jpg"),
("IIkay Gundogan", 12, "/View/Modules/Album/Images/Stickers/Alemanha/IIkay_Gundogan.jpg"),
("Lautaro Martinez", 3, "/View/Modules/Album/Images/Stickers/Argentina/Lautaro_Martinez.jpg"),
("Trent Alexander-Arnold", 8, "/View/Modules/Album/Images/Stickers/Inglaterra/Trent_Alexander_Arnold.jpg"),
("Achraf Hakimi", 16, "/View/Modules/Album/Images/Stickers/Marrocos/Achraf_Hakimi.jpg"),
("Antoine Griezmann", 1, "/View/Modules/Album/Images/Stickers/Franca/Antoine_Griezmann.jpg"),
("Ousmane Dembele", 1, "/View/Modules/Album/Images/Stickers/Franca/Ousmane_Dembele.jpg"),
("Gabriel Jesus", 5, "/View/Modules/Album/Images/Stickers/Brasil/Gabriel_Jesus.jpg"),
("Dusan Vlahovic", 17, "/View/Modules/Album/Images/Stickers/Servia/Dusan_Vlahovic.jpg"),
("Jamal Musiala", 12, "/View/Modules/Album/Images/Stickers/Alemanha/Jamal_Musiala.jpg"),
("Rodri", 14, "/View/Modules/Album/Images/Stickers/Espanha/Rodri.jpg"),
("Romelu Lukaku", 2, "/View/Modules/Album/Images/Stickers/Belgica/Romelu_Lukaku.jpg"),
("Aurelien Tchouameni", 1, "/View/Modules/Album/Images/Stickers/Franca/Aurelien_Tchouameni.jpg"),
("Gavi", 14, "/View/Modules/Album/Images/Stickers/Espanha/Gavi.jpg"),
("Christian Eriksen", 18, "/View/Modules/Album/Images/Stickers/Dinamarca/Christian_Eriksen.jpg"),
("Ederson", 5, "/View/Modules/Album/Images/Stickers/Brasil/Ederson.jpg"),
("Bukayo Saka", 8, "/View/Modules/Album/Images/Stickers/Inglaterra/Bukayo_Saka.jpg"),
("Kalidou Koulibaly", 7, "/View/Modules/Album/Images/Stickers/Senegal/Kalidou_Koulibaly.jpg"),
("Andre Onana", 19, "/View/Modules/Album/Images/Stickers/Camaroes/Andre_Onana.jpg");

Select * From Pais Order By id ASC;

Select * From Figurinha Order By id ASC;